version: "3.8"

services:
  localstack:
    image: localstack/localstack:latest
    environment:
      - AWS_REGION=us-east-2
      - EDGE_PORT=4566
      - SERVICES=s3
      - S3_ENDPOINT_URL=https://localhost:4566
    ports:
      - '4566-4583:4566-4583'
    volumes:
      - "${TEMPDIR:-/tmp/localstack}:/tmp/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"