{
 "title": "week5_monitoring",
 "time": { "from": "2023-03-01T05:05:37.439Z", "to": "2023-03-27T02:00:16.944Z" },
 "panels": [
  {
   "title": "Share of missing values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM evi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "pred_drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM evi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "number of drifted columns",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", num_drifted_columns FROM evi_metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Qantile values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", quantile_values FROM evi_metrics LIMIT 50 "
    }
   ]
  }
 ]
}